name: Service Build

on:
  workflow_dispatch:

  push:

  pull_request:
    types: [opened, edited]

jobs:
  build:
    if: github.event_name != 'pull_request'

    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test with Gradle
        run: ./gradlew check --no-daemon
