name: Gradle Checks

on:
  pull_request:

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          check-latest: true

      - name: Setup and execute Gradle 'check' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
