name: Service Detect Secrets

on:
  workflow_dispatch:

  push:

jobs:
  detect_secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Perform Detect Secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
