name: Service Release

on:
  workflow_dispatch:
    inputs:
      newReleaseVersion:
        description: "Release version"
        required: false
jobs:
  release_version:
    if: github.ref == 'refs/heads/main'
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          check-latest: true

      - name: Setup and execute Gradle 'check' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check

      - run: |
          echo "New release version: ${{ github.event.inputs.newReleaseVersion }}"

      - name: Release version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            release
            -Prelease.forceVersion=${{ github.event.inputs.newReleaseVersion }}
            -Prelease.customUsername=${{ github.actor }}
            -Prelease.customPassword=${{ github.token }}

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
