name: Service Test

on:
  workflow_dispatch:

  push:
    paths:
      - '.github/workflows/test.yml'
      - '.gradle/**'
      - 'config/**'
      - 'src/**'
      - 'build.gradle'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
          cache: gradle

      - name: Test with Gradle
        run: ./gradlew check --no-daemon
